name: mong_c3
channels:
  - defaults
dependencies:
- python>=3.9
- pip>=21
- scikit-image=0.18.1
- pytorch-lightning==2.0.2
- torchmetrics==1.4.3
- numpy==1.26.4
- pip:
   - torch torchvision --index-url https://download.pytorch.org/whl/cu118
   - transformers==4.28.1
   - ftfy
   - regex
   - tqdm
   - git+https://github.com/openai/CLIP.git
   - omegaconf==2.1.1
   - requests
   - timm
   - git+https://github.com/flauted/coco-caption.git@python23
   - wandb
   - pandas
   - scikit-learn
   - evaluate
   - rouge_score
   - einops
   - ema_pytorch
   - accelerate

